nelmio_cors:
    defaults:
        origin_regex: true
        #allow_origin:  ["%env(CORS_ALLOW_ORIGIN)%"]
        allow_origin: ['*']
        allow_headers: ["content-type","X-Auth-Token","accept","authorization","cookies"]
        allow_methods: ["POST", "PUT", "GET", "DELETE", "PATCH", OPTIONS"]
        max_age:       3600
    paths:
        '^/': ~